### ISSUE TITLE
Ownership transfer by mistake?

### ISSUE THREAD

**Issue by icy** [Stephane-D/Icy-ROITooltip#1]
Hi,

I've just got email as below. I think this is sent by mistake. Please have a look

Thanks

> From: GitHub <support@github.com>
> Subject: [GitHub] Repository transfer from @Stephane-D  (Stephane-D/Icy-ROITooltip)
> Date: Sat, 11 Apr 2020 03:26:34 -0700
> 
> Hello icy,
> 
> @Stephane-D wants to transfer the Stephane-D/Icy-ROITooltip repository to icy/Icy-ROITooltip.
> 
> To accept the transfer, visit this link:
> 
>     https://github.com/repositories/transfers/<TOKEN>
> 
> If you don’t accept the transfer, it’ll expire in about a day.
> 
> Questions? Problems? Please contact support@github.com any time.
> 
> Thanks,
> Your friends at GitHub

**Comment by Stephane-D** [comment]
Hi,

Sorry yeah it was a mistake ! I cancelled and fixed that. Thanks for notifying me 😉

Best,

-- 
Stephane Dallongeville
Unité d'Analyse d'Images Biologiques
CNRS UMR 3691
Institut Pasteur
25 rue du Dr. Roux
75724 Paris cedex 15 (FRANCE)

Tel: +33 (0)1 45 68 87 01
Fax: +33 (0)1 40 61 33 30

http://www.bioimageanalysis.org/

De : Ky-Anh Huynh
Envoyé le :samedi 11 avril 2020 12:58
À : Icy-imaging/Icy-ROITooltip
Cc : Stephane Dallongeville; Mention
Objet :[Icy-imaging/Icy-ROITooltip] Ownership transfer by mistake? (#1)

Hi,
I've just got email as below. I think this is sent by mistake. Please have a look
Thanks
From: GitHub support@github.com
Subject: [GitHub] Repository transfer from @Stephane-D (Stephane-D/Icy-ROITooltip)
Date: Sat, 11 Apr 2020 03:26:34 -0700
Hello icy,
@Stephane-D wants to transfer the Stephane-D/Icy-ROITooltip repository to icy/Icy-ROITooltip.
To accept the transfer, visit this link:
https://github.com/repositories/transfers/<TOKEN>

If you don’t accept the transfer, it’ll expire in about a day.
Questions? Problems? Please contact support@github.com any time.
Thanks,
Your friends at GitHub
